### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bry**
Removed redundant dashes from README.md

### CODE REVIEW

**Comment by stevenbarragan** [comment]
@bry the numeric list is gone, now it goes from 1 to 1 :confused:  https://github.com/bry/cheuky_builder/blob/master/README.md

**Comment by stevenbarragan** [comment]
Could you fix it?

**Comment by bry** [comment]
@stevenbarragan Fixed, indenting 4 spaces after each enumeration did the trick.

**Comment by stevenbarragan** [comment]
Could you squash your commits please?

**Comment by stevenbarragan** [comment]
Thanks @bry!

**Pull request merged**
